### ISSUE TITLE
German Umlaut issue

### ISSUE THREAD

**Issue by ChaosEmpire** [ccev/stopwatcher#52]
using a geofence like bö.txt and fitting area names causes

 python3 stop_watcher.py
Traceback (most recent call last):
  File "stop_watcher.py", line 6, in <module>
    from stopwatcher.accepter import DataAccepter
  File "/stopwatcher/stopwatcher/accepter.py", line 23, in <module>
    from .config import config
  File "/stopwatcher/stopwatcher/config.py", line 148, in <module>
    _raw_config = _get_raw_config("config.toml")
  File "/stopwatcher/stopwatcher/config.py", line 134, in _get_raw_config
    raw_config = rtoml.load(_config_file)
  File "/home/xx/.local/lib/python3.8/site-packages/rtoml/__init__.py", line 25, in load
    return loads(toml)
  File "/home/xx/.local/lib/python3.8/site-packages/rtoml/__init__.py", line 34, in loads
    return _rtoml.deserialize(toml)
_rtoml.TomlParsingError: unexpected character found: `\u{f6}` at line 143 column 9

**Comment by ccev** [comment]
As per the [toml spec](https://toml.io/en/v0.4.0#table) "Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-)". Just go with i.e. `u` or `ue` instead of `ü`.
